---
name: Word
title: Word
---
markdown:kramdown

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from

# SEO Stuff
author: Charlie Joseph
description: Gleanings from The Word
lang: en
locale: en_GB
url: "https://antleo.com/Word"
baseurl: ""

